//  Created by TagCommander on 22/03/2023.
//  Version : 5.3.0
//
//  Copyright (c) 2023 Commanders Act. All rights reserved.
//
// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE BY HAND.

#ifndef __SERVERSIDE_GENERATED_H__
#define __SERVERSIDE_GENERATED_H__

#import <Foundation/Foundation.h>

extern NSString *const kTCServerSideVersion;

extern NSString *const kTCReleaseDate;
extern NSString *const kTCReleaseTime;




#endif //__SERVERSIDE_GENERATED_H__
